# Generated by Django 5.0.3 on 2026-04-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('realized_pl', models.FloatField(default=0.0)),
                ('units', models.FloatField()),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('take_profit', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('realized_pl', models.FloatField(default=0.0)),
                ('units', models.FloatField()),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('take_profit', models.FloatField(null=True)),
                ('margin_required', models.FloatField()),
                ('close_price', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
