# Generated by Django 5.0.3 on 2026-07-08 04:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('state', models.CharField(max_length=16)),
                ('units', models.FloatField()),
                ('realized_pl', models.FloatField(default=0.0)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(null=True)),
                ('margin_required', models.FloatField()),
                ('close_price', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriggerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('state', models.CharField(max_length=16)),
                ('units', models.FloatField()),
                ('realized_pl', models.FloatField(default=0.0)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('take_profit', models.FloatField(null=True)),
                ('order_type', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
                ('trade', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
