# Generated by Django 5.0.3 on 2025-11-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.FloatField(null=True),
        ),
    ]
