# Generated by Django 5.0.3 on 2026-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trade_stop_loss_trade_take_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='units',
            field=models.FloatField(),
        ),
    ]
