# Generated by Django 5.0.3 on 2024-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='realized_pl',
            field=models.FloatField(default=0.0),
        ),
    ]
