# Generated by Django 5.0.3 on 2024-03-29 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trade_realized_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
