# Generated by Django 5.0.3 on 2024-03-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
