# Generated by Django 5.0.3 on 2024-03-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='start_time',
        ),
        migrations.AddField(
            model_name='account',
            name='time_delta',
            field=models.IntegerField(default=0),
        ),
    ]
