# Generated by Django 5.0.3 on 2024-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_account_start_time_account_time_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='detla_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
